version: "3.6"

services:
  app:
    build:
      context: ../../
      dockerfile: .config/docker/dev/Dockerfile

    environment:
      PORT: ${PORT}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ../../:/app
    restart: always
